---
source: crates/ruff_linter/src/rules/flake8_async/mod.rs
snapshot_kind: text
---
ASYNC102_old.py:43:13: ASYNC102 shield it!
   |
41 |     except Exception as e:
42 |         with anyio.CancelScope(shield=False):
43 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
44 |         with anyio.CancelScope():
45 |             await asyncio.sleep(1)  # fail
   |

ASYNC102_old.py:45:13: ASYNC102 shield it!
   |
43 |             await asyncio.sleep(1)  # fail
44 |         with anyio.CancelScope():
45 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
46 |         with anyio.move_on_after(shield=False):
47 |             await asyncio.sleep(1)  # fail
   |

ASYNC102_old.py:47:13: ASYNC102 shield it!
   |
45 |             await asyncio.sleep(1)  # fail
46 |         with anyio.move_on_after(shield=False):
47 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
48 |         with anyio.move_on_after():
49 |             await asyncio.sleep(1)  # fail
   |

ASYNC102_old.py:49:13: ASYNC102 shield it!
   |
47 |             await asyncio.sleep(1)  # fail
48 |         with anyio.move_on_after():
49 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
50 |         with anyio.fail_after(shield=False):
51 |             await asyncio.sleep(1)  # fail
   |

ASYNC102_old.py:51:13: ASYNC102 shield it!
   |
49 |             await asyncio.sleep(1)  # fail
50 |         with anyio.fail_after(shield=False):
51 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
52 |         with anyio.fail_after():
53 |             await asyncio.sleep(1)  # fail
   |

ASYNC102_old.py:53:13: ASYNC102 shield it!
   |
51 |             await asyncio.sleep(1)  # fail
52 |         with anyio.fail_after():
53 |             await asyncio.sleep(1)  # fail
   |             ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
   |

ASYNC102_old.py:67:9: ASYNC102 shield it!
   |
65 |         pass
66 |     except Exception as e:
67 |         await asyncio.sleep(1)  # fail
   |         ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
   |

ASYNC102_old.py:74:9: ASYNC102 shield it!
   |
72 |         pass
73 |     except asyncio.CancelledError as e:
74 |         await asyncio.sleep(1)  # fail
   |         ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
   |

ASYNC102_old.py:81:9: ASYNC102 shield it!
   |
79 |         pass
80 |     except ((ZeroDivisionError, Exception), ValueError) as e:
81 |         await asyncio.sleep(1)  # fail
   |         ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
   |

ASYNC102_old.py:88:9: ASYNC102 shield it!
   |
86 |         pass
87 |     finally:
88 |         await asyncio.sleep(1)  # fail
   |         ^^^^^^^^^^^^^^^^^^^^^^ ASYNC102
89 | 
90 | async def fail_async_with():
   |

ASYNC102_old.py:94:9: ASYNC102 shield it!
   |
92 |           pass
93 |       finally:
94 |           async with my_own_async_manager():  # fail
   |  _________^
95 | |             pass
   | |________________^ ASYNC102
   |
